// <auto-generated />
using System;
using Client_ui.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Client_ui.Migrations
{
    [DbContext(typeof(WorkoutAppDbContext))]
    partial class WorkoutAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Client_ui.Domain.DTO.AddExercises+ExerciseDTOs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ExeciseWeight")
                        .HasColumnType("real");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExerciseQuality")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseReps")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseSets")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("ExerciseTime")
                        .HasColumnType("time");

                    b.Property<Guid?>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("ExerciseDTOs");
                });

            modelBuilder.Entity("Client_ui.Domain.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExcersiseQuality")
                        .HasColumnType("int");

                    b.Property<float>("ExeciseWeight")
                        .HasColumnType("real");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExerciseReps")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseSets")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("ExerciseTime")
                        .HasColumnType("time");

                    b.Property<float>("ExerciseVolume")
                        .HasColumnType("real");

                    b.Property<Guid>("WorkoutFK")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutFK");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Client_ui.Domain.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("WorkoutDate")
                        .HasColumnType("date");

                    b.Property<string>("WorkoutName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkoutQuality")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("WorkoutTime")
                        .HasColumnType("time");

                    b.Property<float>("WorkoutVolume")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("Client_ui.Domain.DTO.AddExercises+ExerciseDTOs", b =>
                {
                    b.HasOne("Client_ui.Domain.Workout", null)
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutId");
                });

            modelBuilder.Entity("Client_ui.Domain.Exercise", b =>
                {
                    b.HasOne("Client_ui.Domain.Workout", "Workout")
                        .WithMany()
                        .HasForeignKey("WorkoutFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("Client_ui.Domain.Workout", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
